apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netology
  template:
    metadata:
      labels:
        app: netology
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "0.5"
            limits:
              memory: "32Mi"
              cpu: "1"
        - name: multitool
          image: wbitt/network-multitool
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: HTTPS_PORT
              value: "8443"
          ports:
            - containerPort: 8080
            - containerPort: 8443
          resources:
            requests:
              memory: "32Mi"
              cpu: "0.5"
            limits:
              memory: "32Mi"
              cpu: "1"
